[2025-03-29T11:08:27.266+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_aqi_multiple_cities.fetch_aqi_all_cities scheduled__2025-03-29T10:00:00+00:00 [queued]>
[2025-03-29T11:08:27.269+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_aqi_multiple_cities.fetch_aqi_all_cities scheduled__2025-03-29T10:00:00+00:00 [queued]>
[2025-03-29T11:08:27.269+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-03-29T11:08:27.274+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): fetch_aqi_all_cities> on 2025-03-29 10:00:00+00:00
[2025-03-29T11:08:27.276+0000] {standard_task_runner.py:60} INFO - Started process 18265 to run task
[2025-03-29T11:08:27.278+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'fetch_aqi_multiple_cities', 'fetch_aqi_all_cities', 'scheduled__2025-03-29T10:00:00+00:00', '--job-id', '101', '--raw', '--subdir', 'DAGS_FOLDER/fetch_multiple_cities.py', '--cfg-path', '/tmp/tmppbrwp6p_']
[2025-03-29T11:08:27.279+0000] {standard_task_runner.py:88} INFO - Job 101: Subtask fetch_aqi_all_cities
[2025-03-29T11:08:27.285+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-29T11:08:27.299+0000] {task_command.py:423} INFO - Running <TaskInstance: fetch_aqi_multiple_cities.fetch_aqi_all_cities scheduled__2025-03-29T10:00:00+00:00 [running]> on host f5300fe43025
[2025-03-29T11:08:27.332+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_aqi_multiple_cities' AIRFLOW_CTX_TASK_ID='fetch_aqi_all_cities' AIRFLOW_CTX_EXECUTION_DATE='2025-03-29T10:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-29T10:00:00+00:00'
[2025-03-29T11:08:27.337+0000] {fetch_multiple_cities.py:62} ERROR - ⚠️ Error fetching data for Bangkok: HTTPConnectionPool(host='api.airvisual.com', port=80): Max retries exceeded with url: /v2/city?city=Bangkok&state=Bangkok&country=Thailand&key=4fb76e79-4433-4b76-9866-f8fdf19a9d33 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff8ed27730>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2025-03-29T11:08:42.605+0000] {fetch_multiple_cities.py:51} INFO - ✅ Chiang Mai: AQI = 172
[2025-03-29T11:08:42.617+0000] {base.py:83} INFO - Using connection ID 'postgres_conn' for task execution.
[2025-03-29T11:08:42.622+0000] {sql.py:450} INFO - Running statement: 
                        INSERT INTO air_quality_data (city, aqi, timestamp_utc)
                        VALUES (%s, %s, %s);
                    , parameters: ('Chiang Mai', 172, datetime.datetime(2025, 3, 29, 18, 8, 27, 332905, tzinfo=<DstTzInfo 'Asia/Bangkok' +07+7:00:00 STD>))
[2025-03-29T11:08:42.624+0000] {sql.py:459} INFO - Rows affected: 1
[2025-03-29T11:25:06.242+0000] {fetch_multiple_cities.py:51} INFO - ✅ Ratchaburi: AQI = 82
[2025-03-29T11:25:06.259+0000] {base.py:83} INFO - Using connection ID 'postgres_conn' for task execution.
[2025-03-29T11:25:06.263+0000] {sql.py:450} INFO - Running statement: 
                        INSERT INTO air_quality_data (city, aqi, timestamp_utc)
                        VALUES (%s, %s, %s);
                    , parameters: ('Ratchaburi', 82, datetime.datetime(2025, 3, 29, 18, 8, 27, 332905, tzinfo=<DstTzInfo 'Asia/Bangkok' +07+7:00:00 STD>))
[2025-03-29T11:25:06.264+0000] {sql.py:459} INFO - Rows affected: 1
[2025-03-29T11:25:21.566+0000] {fetch_multiple_cities.py:51} INFO - ✅ Rua Yai: AQI = 97
[2025-03-29T11:25:21.577+0000] {base.py:83} INFO - Using connection ID 'postgres_conn' for task execution.
[2025-03-29T11:25:21.581+0000] {sql.py:450} INFO - Running statement: 
                        INSERT INTO air_quality_data (city, aqi, timestamp_utc)
                        VALUES (%s, %s, %s);
                    , parameters: ('Rua Yai', 97, datetime.datetime(2025, 3, 29, 18, 8, 27, 332905, tzinfo=<DstTzInfo 'Asia/Bangkok' +07+7:00:00 STD>))
[2025-03-29T11:25:21.583+0000] {sql.py:459} INFO - Rows affected: 1
[2025-03-29T11:26:52.508+0000] {fetch_multiple_cities.py:51} INFO - ✅ Mueang Nonthaburi: AQI = 102
[2025-03-29T11:26:52.523+0000] {base.py:83} INFO - Using connection ID 'postgres_conn' for task execution.
[2025-03-29T11:26:52.527+0000] {sql.py:450} INFO - Running statement: 
                        INSERT INTO air_quality_data (city, aqi, timestamp_utc)
                        VALUES (%s, %s, %s);
                    , parameters: ('Mueang Nonthaburi', 102, datetime.datetime(2025, 3, 29, 18, 8, 27, 332905, tzinfo=<DstTzInfo 'Asia/Bangkok' +07+7:00:00 STD>))
[2025-03-29T11:26:52.528+0000] {sql.py:459} INFO - Rows affected: 1
[2025-03-29T11:27:07.548+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-03-29T11:27:07.558+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=fetch_aqi_multiple_cities, task_id=fetch_aqi_all_cities, execution_date=20250329T100000, start_date=20250329T110827, end_date=20250329T112707
[2025-03-29T11:27:07.606+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-29T11:27:07.618+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
