[2025-03-29T12:05:43.553+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: validate_aqi_data.validate_aqi manual__2025-03-29T12:05:42.606141+00:00 [queued]>
[2025-03-29T12:05:43.555+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: validate_aqi_data.validate_aqi manual__2025-03-29T12:05:42.606141+00:00 [queued]>
[2025-03-29T12:05:43.555+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-03-29T12:05:43.559+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): validate_aqi> on 2025-03-29 12:05:42.606141+00:00
[2025-03-29T12:05:43.561+0000] {standard_task_runner.py:60} INFO - Started process 19417 to run task
[2025-03-29T12:05:43.563+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'validate_aqi_data', 'validate_aqi', 'manual__2025-03-29T12:05:42.606141+00:00', '--job-id', '104', '--raw', '--subdir', 'DAGS_FOLDER/validate_aqi_data.py', '--cfg-path', '/tmp/tmp36j32fnn']
[2025-03-29T12:05:43.563+0000] {standard_task_runner.py:88} INFO - Job 104: Subtask validate_aqi
[2025-03-29T12:05:43.569+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-29T12:05:43.580+0000] {task_command.py:423} INFO - Running <TaskInstance: validate_aqi_data.validate_aqi manual__2025-03-29T12:05:42.606141+00:00 [running]> on host f5300fe43025
[2025-03-29T12:05:43.607+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='validate_aqi_data' AIRFLOW_CTX_TASK_ID='validate_aqi' AIRFLOW_CTX_EXECUTION_DATE='2025-03-29T12:05:42.606141+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-29T12:05:42.606141+00:00'
[2025-03-29T12:05:43.610+0000] {base.py:83} INFO - Using connection ID 'postgres_conn' for task execution.
[2025-03-29T12:05:43.611+0000] {validate_aqi_data.py:55} INFO - ✅ Data validation ผ่านทั้งหมด
[2025-03-29T12:05:43.611+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-03-29T12:05:43.614+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=validate_aqi_data, task_id=validate_aqi, execution_date=20250329T120542, start_date=20250329T120543, end_date=20250329T120543
[2025-03-29T12:05:43.619+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-29T12:05:43.625+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
