[2025-03-30T10:35:19.451+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_aqi_multiple_cities.fetch_aqi_all_cities scheduled__2025-03-30T09:00:00+00:00 [queued]>
[2025-03-30T10:35:19.455+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_aqi_multiple_cities.fetch_aqi_all_cities scheduled__2025-03-30T09:00:00+00:00 [queued]>
[2025-03-30T10:35:19.456+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-03-30T10:35:19.463+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): fetch_aqi_all_cities> on 2025-03-30 09:00:00+00:00
[2025-03-30T10:35:19.465+0000] {standard_task_runner.py:60} INFO - Started process 30958 to run task
[2025-03-30T10:35:19.466+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'fetch_aqi_multiple_cities', 'fetch_aqi_all_cities', 'scheduled__2025-03-30T09:00:00+00:00', '--job-id', '128', '--raw', '--subdir', 'DAGS_FOLDER/fetch_multiple_cities.py', '--cfg-path', '/tmp/tmpekzpqa9j']
[2025-03-30T10:35:19.467+0000] {standard_task_runner.py:88} INFO - Job 128: Subtask fetch_aqi_all_cities
[2025-03-30T10:35:19.473+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-30T10:35:19.489+0000] {task_command.py:423} INFO - Running <TaskInstance: fetch_aqi_multiple_cities.fetch_aqi_all_cities scheduled__2025-03-30T09:00:00+00:00 [running]> on host f5300fe43025
[2025-03-30T10:35:19.539+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_aqi_multiple_cities' AIRFLOW_CTX_TASK_ID='fetch_aqi_all_cities' AIRFLOW_CTX_EXECUTION_DATE='2025-03-30T09:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-30T09:00:00+00:00'
[2025-03-30T10:35:19.546+0000] {fetch_multiple_cities.py:62} ERROR - ⚠️ Error fetching data for Bangkok: HTTPConnectionPool(host='api.airvisual.com', port=80): Max retries exceeded with url: /v2/city?city=Bangkok&state=Bangkok&country=Thailand&key=4fb76e79-4433-4b76-9866-f8fdf19a9d33 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff8ed285b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2025-03-30T10:35:34.961+0000] {fetch_multiple_cities.py:51} INFO - ✅ Chiang Mai: AQI = 168
[2025-03-30T10:35:34.973+0000] {base.py:83} INFO - Using connection ID 'postgres_conn' for task execution.
[2025-03-30T10:35:34.977+0000] {sql.py:450} INFO - Running statement: 
                        INSERT INTO air_quality_data (city, aqi, timestamp_utc)
                        VALUES (%s, %s, %s);
                    , parameters: ('Chiang Mai', 168, datetime.datetime(2025, 3, 30, 17, 35, 19, 540283, tzinfo=<DstTzInfo 'Asia/Bangkok' +07+7:00:00 STD>))
[2025-03-30T10:35:34.979+0000] {sql.py:459} INFO - Rows affected: 1
[2025-03-30T11:05:33.925+0000] {fetch_multiple_cities.py:51} INFO - ✅ Ratchaburi: AQI = 54
[2025-03-30T11:05:33.928+0000] {base.py:83} INFO - Using connection ID 'postgres_conn' for task execution.
[2025-03-30T11:05:33.930+0000] {sql.py:450} INFO - Running statement: 
                        INSERT INTO air_quality_data (city, aqi, timestamp_utc)
                        VALUES (%s, %s, %s);
                    , parameters: ('Ratchaburi', 54, datetime.datetime(2025, 3, 30, 17, 35, 19, 540283, tzinfo=<DstTzInfo 'Asia/Bangkok' +07+7:00:00 STD>))
[2025-03-30T11:05:33.930+0000] {sql.py:459} INFO - Rows affected: 1
[2025-03-30T11:05:49.155+0000] {fetch_multiple_cities.py:51} INFO - ✅ Rua Yai: AQI = 110
[2025-03-30T11:05:49.159+0000] {base.py:83} INFO - Using connection ID 'postgres_conn' for task execution.
[2025-03-30T11:05:49.160+0000] {sql.py:450} INFO - Running statement: 
                        INSERT INTO air_quality_data (city, aqi, timestamp_utc)
                        VALUES (%s, %s, %s);
                    , parameters: ('Rua Yai', 110, datetime.datetime(2025, 3, 30, 17, 35, 19, 540283, tzinfo=<DstTzInfo 'Asia/Bangkok' +07+7:00:00 STD>))
[2025-03-30T11:05:49.161+0000] {sql.py:459} INFO - Rows affected: 1
[2025-03-30T11:21:02.513+0000] {fetch_multiple_cities.py:51} INFO - ✅ Mueang Nonthaburi: AQI = 94
[2025-03-30T11:21:02.516+0000] {base.py:83} INFO - Using connection ID 'postgres_conn' for task execution.
[2025-03-30T11:21:02.519+0000] {sql.py:450} INFO - Running statement: 
                        INSERT INTO air_quality_data (city, aqi, timestamp_utc)
                        VALUES (%s, %s, %s);
                    , parameters: ('Mueang Nonthaburi', 94, datetime.datetime(2025, 3, 30, 17, 35, 19, 540283, tzinfo=<DstTzInfo 'Asia/Bangkok' +07+7:00:00 STD>))
[2025-03-30T11:21:02.519+0000] {sql.py:459} INFO - Rows affected: 1
[2025-03-30T11:21:17.534+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-03-30T11:21:17.545+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=fetch_aqi_multiple_cities, task_id=fetch_aqi_all_cities, execution_date=20250330T090000, start_date=20250330T103519, end_date=20250330T112117
[2025-03-30T11:21:17.594+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:21:17.603+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
