[2025-03-28T02:00:00.383+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_aqi_multiple_cities.fetch_aqi_all_cities scheduled__2025-03-28T01:00:00+00:00 [queued]>
[2025-03-28T02:00:00.386+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_aqi_multiple_cities.fetch_aqi_all_cities scheduled__2025-03-28T01:00:00+00:00 [queued]>
[2025-03-28T02:00:00.386+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-03-28T02:00:00.393+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): fetch_aqi_all_cities> on 2025-03-28 01:00:00+00:00
[2025-03-28T02:00:00.397+0000] {standard_task_runner.py:60} INFO - Started process 420 to run task
[2025-03-28T02:00:00.398+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'fetch_aqi_multiple_cities', 'fetch_aqi_all_cities', 'scheduled__2025-03-28T01:00:00+00:00', '--job-id', '65', '--raw', '--subdir', 'DAGS_FOLDER/fetch_multiple_cities.py', '--cfg-path', '/tmp/tmp0h0rnpg4']
[2025-03-28T02:00:00.399+0000] {standard_task_runner.py:88} INFO - Job 65: Subtask fetch_aqi_all_cities
[2025-03-28T02:00:00.405+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-28T02:00:00.420+0000] {task_command.py:423} INFO - Running <TaskInstance: fetch_aqi_multiple_cities.fetch_aqi_all_cities scheduled__2025-03-28T01:00:00+00:00 [running]> on host bee80cc57b6d
[2025-03-28T02:00:00.455+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_aqi_multiple_cities' AIRFLOW_CTX_TASK_ID='fetch_aqi_all_cities' AIRFLOW_CTX_EXECUTION_DATE='2025-03-28T01:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-28T01:00:00+00:00'
[2025-03-28T02:00:00.769+0000] {fetch_multiple_cities.py:51} INFO - ✅ Bangkok: AQI = 140
[2025-03-28T02:00:00.778+0000] {base.py:83} INFO - Using connection ID 'postgres_conn' for task execution.
[2025-03-28T02:00:00.791+0000] {sql.py:450} INFO - Running statement: 
                        INSERT INTO air_quality_data (city, aqi, timestamp_utc)
                        VALUES (%s, %s, %s);
                    , parameters: ('Bangkok', 140, datetime.datetime(2025, 3, 28, 9, 0, 0, 456207, tzinfo=<DstTzInfo 'Asia/Bangkok' +07+7:00:00 STD>))
[2025-03-28T02:00:00.792+0000] {sql.py:459} INFO - Rows affected: 1
[2025-03-28T02:00:16.054+0000] {fetch_multiple_cities.py:51} INFO - ✅ Chiang Mai: AQI = 179
[2025-03-28T02:00:16.063+0000] {base.py:83} INFO - Using connection ID 'postgres_conn' for task execution.
[2025-03-28T02:00:16.067+0000] {sql.py:450} INFO - Running statement: 
                        INSERT INTO air_quality_data (city, aqi, timestamp_utc)
                        VALUES (%s, %s, %s);
                    , parameters: ('Chiang Mai', 179, datetime.datetime(2025, 3, 28, 9, 0, 0, 456207, tzinfo=<DstTzInfo 'Asia/Bangkok' +07+7:00:00 STD>))
[2025-03-28T02:00:16.068+0000] {sql.py:459} INFO - Rows affected: 1
[2025-03-28T02:00:31.365+0000] {fetch_multiple_cities.py:51} INFO - ✅ Ratchaburi: AQI = 73
[2025-03-28T02:00:31.375+0000] {base.py:83} INFO - Using connection ID 'postgres_conn' for task execution.
[2025-03-28T02:00:31.379+0000] {sql.py:450} INFO - Running statement: 
                        INSERT INTO air_quality_data (city, aqi, timestamp_utc)
                        VALUES (%s, %s, %s);
                    , parameters: ('Ratchaburi', 73, datetime.datetime(2025, 3, 28, 9, 0, 0, 456207, tzinfo=<DstTzInfo 'Asia/Bangkok' +07+7:00:00 STD>))
[2025-03-28T02:00:31.380+0000] {sql.py:459} INFO - Rows affected: 1
[2025-03-28T02:00:46.665+0000] {fetch_multiple_cities.py:60} WARNING - ❌ API error for Rua Yai: 429
[2025-03-28T02:01:01.999+0000] {fetch_multiple_cities.py:51} INFO - ✅ Mueang Nonthaburi: AQI = 152
[2025-03-28T02:01:02.007+0000] {base.py:83} INFO - Using connection ID 'postgres_conn' for task execution.
[2025-03-28T02:01:02.011+0000] {sql.py:450} INFO - Running statement: 
                        INSERT INTO air_quality_data (city, aqi, timestamp_utc)
                        VALUES (%s, %s, %s);
                    , parameters: ('Mueang Nonthaburi', 152, datetime.datetime(2025, 3, 28, 9, 0, 0, 456207, tzinfo=<DstTzInfo 'Asia/Bangkok' +07+7:00:00 STD>))
[2025-03-28T02:01:02.012+0000] {sql.py:459} INFO - Rows affected: 1
[2025-03-28T02:01:17.024+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-03-28T02:01:17.032+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=fetch_aqi_multiple_cities, task_id=fetch_aqi_all_cities, execution_date=20250328T010000, start_date=20250328T020000, end_date=20250328T020117
[2025-03-28T02:01:17.048+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-28T02:01:17.056+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
