[2025-03-27T15:06:02.112+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_aqi_multiple_cities.fetch_aqi_all_cities manual__2025-03-27T15:06:01.024296+00:00 [queued]>
[2025-03-27T15:06:02.114+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_aqi_multiple_cities.fetch_aqi_all_cities manual__2025-03-27T15:06:01.024296+00:00 [queued]>
[2025-03-27T15:06:02.115+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-03-27T15:06:02.119+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): fetch_aqi_all_cities> on 2025-03-27 15:06:01.024296+00:00
[2025-03-27T15:06:02.122+0000] {standard_task_runner.py:60} INFO - Started process 1495 to run task
[2025-03-27T15:06:02.123+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'fetch_aqi_multiple_cities', 'fetch_aqi_all_cities', 'manual__2025-03-27T15:06:01.024296+00:00', '--job-id', '48', '--raw', '--subdir', 'DAGS_FOLDER/fetch_multiple_cities.py', '--cfg-path', '/tmp/tmpeh2at21j']
[2025-03-27T15:06:02.124+0000] {standard_task_runner.py:88} INFO - Job 48: Subtask fetch_aqi_all_cities
[2025-03-27T15:06:02.131+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-27T15:06:02.143+0000] {task_command.py:423} INFO - Running <TaskInstance: fetch_aqi_multiple_cities.fetch_aqi_all_cities manual__2025-03-27T15:06:01.024296+00:00 [running]> on host 75125d84c351
[2025-03-27T15:06:02.172+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_aqi_multiple_cities' AIRFLOW_CTX_TASK_ID='fetch_aqi_all_cities' AIRFLOW_CTX_EXECUTION_DATE='2025-03-27T15:06:01.024296+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-27T15:06:01.024296+00:00'
[2025-03-27T15:06:02.472+0000] {fetch_multiple_cities.py:51} INFO - ✅ Bangkok: AQI = 117
[2025-03-27T15:06:02.478+0000] {base.py:83} INFO - Using connection ID 'postgres_conn' for task execution.
[2025-03-27T15:06:02.480+0000] {sql.py:450} INFO - Running statement: 
                        INSERT INTO air_quality_data (city, aqi, timestamp_utc)
                        VALUES (%s, %s, %s);
                    , parameters: ('Bangkok', 117, datetime.datetime(2025, 3, 27, 22, 6, 2, 173282, tzinfo=<DstTzInfo 'Asia/Bangkok' +07+7:00:00 STD>))
[2025-03-27T15:06:02.480+0000] {sql.py:459} INFO - Rows affected: 1
[2025-03-27T15:06:04.794+0000] {fetch_multiple_cities.py:51} INFO - ✅ Chiang Mai: AQI = 155
[2025-03-27T15:06:04.802+0000] {base.py:83} INFO - Using connection ID 'postgres_conn' for task execution.
[2025-03-27T15:06:04.806+0000] {sql.py:450} INFO - Running statement: 
                        INSERT INTO air_quality_data (city, aqi, timestamp_utc)
                        VALUES (%s, %s, %s);
                    , parameters: ('Chiang Mai', 155, datetime.datetime(2025, 3, 27, 22, 6, 2, 173282, tzinfo=<DstTzInfo 'Asia/Bangkok' +07+7:00:00 STD>))
[2025-03-27T15:06:04.807+0000] {sql.py:459} INFO - Rows affected: 1
[2025-03-27T15:06:07.190+0000] {fetch_multiple_cities.py:51} INFO - ✅ Ratchaburi: AQI = 64
[2025-03-27T15:06:07.195+0000] {base.py:83} INFO - Using connection ID 'postgres_conn' for task execution.
[2025-03-27T15:06:07.196+0000] {sql.py:450} INFO - Running statement: 
                        INSERT INTO air_quality_data (city, aqi, timestamp_utc)
                        VALUES (%s, %s, %s);
                    , parameters: ('Ratchaburi', 64, datetime.datetime(2025, 3, 27, 22, 6, 2, 173282, tzinfo=<DstTzInfo 'Asia/Bangkok' +07+7:00:00 STD>))
[2025-03-27T15:06:07.197+0000] {sql.py:459} INFO - Rows affected: 1
[2025-03-27T15:06:09.506+0000] {fetch_multiple_cities.py:60} WARNING - ❌ API error for Rua Yai: 429
[2025-03-27T15:06:11.740+0000] {fetch_multiple_cities.py:60} WARNING - ❌ API error for Mueang Nonthaburi: 429
[2025-03-27T15:06:13.743+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-03-27T15:06:13.756+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=fetch_aqi_multiple_cities, task_id=fetch_aqi_all_cities, execution_date=20250327T150601, start_date=20250327T150602, end_date=20250327T150613
[2025-03-27T15:06:13.800+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-27T15:06:13.812+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
