[2025-03-27T17:00:00.784+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_aqi_multiple_cities.fetch_aqi_all_cities scheduled__2025-03-27T16:00:00+00:00 [queued]>
[2025-03-27T17:00:00.788+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_aqi_multiple_cities.fetch_aqi_all_cities scheduled__2025-03-27T16:00:00+00:00 [queued]>
[2025-03-27T17:00:00.788+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-03-27T17:00:00.794+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): fetch_aqi_all_cities> on 2025-03-27 16:00:00+00:00
[2025-03-27T17:00:00.796+0000] {standard_task_runner.py:60} INFO - Started process 4709 to run task
[2025-03-27T17:00:00.798+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'fetch_aqi_multiple_cities', 'fetch_aqi_all_cities', 'scheduled__2025-03-27T16:00:00+00:00', '--job-id', '59', '--raw', '--subdir', 'DAGS_FOLDER/fetch_multiple_cities.py', '--cfg-path', '/tmp/tmpsiauehkv']
[2025-03-27T17:00:00.799+0000] {standard_task_runner.py:88} INFO - Job 59: Subtask fetch_aqi_all_cities
[2025-03-27T17:00:00.805+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-27T17:00:00.818+0000] {task_command.py:423} INFO - Running <TaskInstance: fetch_aqi_multiple_cities.fetch_aqi_all_cities scheduled__2025-03-27T16:00:00+00:00 [running]> on host 75125d84c351
[2025-03-27T17:00:00.848+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_aqi_multiple_cities' AIRFLOW_CTX_TASK_ID='fetch_aqi_all_cities' AIRFLOW_CTX_EXECUTION_DATE='2025-03-27T16:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-27T16:00:00+00:00'
[2025-03-27T17:00:01.190+0000] {fetch_multiple_cities.py:51} INFO - ✅ Bangkok: AQI = 118
[2025-03-27T17:00:01.201+0000] {base.py:83} INFO - Using connection ID 'postgres_conn' for task execution.
[2025-03-27T17:00:01.204+0000] {sql.py:450} INFO - Running statement: 
                        INSERT INTO air_quality_data (city, aqi, timestamp_utc)
                        VALUES (%s, %s, %s);
                    , parameters: ('Bangkok', 118, datetime.datetime(2025, 3, 28, 0, 0, 0, 849733, tzinfo=<DstTzInfo 'Asia/Bangkok' +07+7:00:00 STD>))
[2025-03-27T17:00:01.205+0000] {sql.py:459} INFO - Rows affected: 1
[2025-03-27T17:00:16.457+0000] {fetch_multiple_cities.py:51} INFO - ✅ Chiang Mai: AQI = 157
[2025-03-27T17:00:16.468+0000] {base.py:83} INFO - Using connection ID 'postgres_conn' for task execution.
[2025-03-27T17:00:16.474+0000] {sql.py:450} INFO - Running statement: 
                        INSERT INTO air_quality_data (city, aqi, timestamp_utc)
                        VALUES (%s, %s, %s);
                    , parameters: ('Chiang Mai', 157, datetime.datetime(2025, 3, 28, 0, 0, 0, 849733, tzinfo=<DstTzInfo 'Asia/Bangkok' +07+7:00:00 STD>))
[2025-03-27T17:00:16.475+0000] {sql.py:459} INFO - Rows affected: 1
[2025-03-27T17:00:31.716+0000] {fetch_multiple_cities.py:51} INFO - ✅ Ratchaburi: AQI = 66
[2025-03-27T17:00:31.725+0000] {base.py:83} INFO - Using connection ID 'postgres_conn' for task execution.
[2025-03-27T17:00:31.730+0000] {sql.py:450} INFO - Running statement: 
                        INSERT INTO air_quality_data (city, aqi, timestamp_utc)
                        VALUES (%s, %s, %s);
                    , parameters: ('Ratchaburi', 66, datetime.datetime(2025, 3, 28, 0, 0, 0, 849733, tzinfo=<DstTzInfo 'Asia/Bangkok' +07+7:00:00 STD>))
[2025-03-27T17:00:31.731+0000] {sql.py:459} INFO - Rows affected: 1
[2025-03-27T17:00:46.954+0000] {fetch_multiple_cities.py:60} WARNING - ❌ API error for Rua Yai: 429
[2025-03-27T17:01:02.201+0000] {fetch_multiple_cities.py:51} INFO - ✅ Mueang Nonthaburi: AQI = 118
[2025-03-27T17:01:02.211+0000] {base.py:83} INFO - Using connection ID 'postgres_conn' for task execution.
[2025-03-27T17:01:02.216+0000] {sql.py:450} INFO - Running statement: 
                        INSERT INTO air_quality_data (city, aqi, timestamp_utc)
                        VALUES (%s, %s, %s);
                    , parameters: ('Mueang Nonthaburi', 118, datetime.datetime(2025, 3, 28, 0, 0, 0, 849733, tzinfo=<DstTzInfo 'Asia/Bangkok' +07+7:00:00 STD>))
[2025-03-27T17:01:02.217+0000] {sql.py:459} INFO - Rows affected: 1
[2025-03-27T17:01:17.233+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-03-27T17:01:17.243+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=fetch_aqi_multiple_cities, task_id=fetch_aqi_all_cities, execution_date=20250327T160000, start_date=20250327T170000, end_date=20250327T170117
[2025-03-27T17:01:17.276+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-27T17:01:17.285+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
